### ISSUE TITLE
/tmp/wpa_ctrl socket deleted if the same process have multiple interfaces

### ISSUE THREAD

**Issue by suhrm** [sauyon/wpa-ctrl-rs#6]
Line [95](https://github.com/spease/wpa-ctrl-rs/blob/e37eeb0a9b58cde12bc9825515caaaadcbf49fa6/src/wpactrl.rs#L95) in wpactrl.rs deletes already existing wpa_ctrl sockets for the same process. This will result in a timeout on the [select ](https://github.com/spease/wpa-ctrl-rs/blob/master/src/wpactrl.rs#L159)if multiple  Wi-Fi interfaces (wpa_supplicants) are handled by the same application.

Deletion of line 95 resolves this issue,see my [fork](https://github.com/suhrm/wpa-ctrl-rs/commit/1b301a427425227e1376a6e7ed6f15a5ee8b40d7), however I have not checked if this introduces other side-effects.

Regards.

**Comment by spease** [comment]
It's been awhile since I worked on this, so I don't remember exactly the situation that prompted me to add it, but it should only come up when the attempt to bind would error out anyway. You're seeing it succeed when you remove it?

**Comment by apbr** [comment]
Assume we want to connect to interface1 and interface2.

First we connect to interface1:
Assuming our PID is `1464` wpactrl will use the socket `/tmp/wpa_ctrl_1464-1`.

Then we try to connect to interface2:
wpactrl will try to use `/tmp/wpa_ctrl_1464-1` again. As this socket is already in use it will fail with `std::io::ErrorKind::AddrInUse`. So wpactrl deletes this socket and binds to interface2 using `/tmp/wpa_ctrl_1464-2`.
But the deletion of `/tmp/wpa_ctrl_1464-1` broke the connection to interface1.

I guess you intended to delete the socket in case the error was **not**  `std::io::ErrorKind::AddrInUse`. Therefore the code should look like this:
``` Rust
    Err(ref e) if counter < 2 && e.kind() == std::io::ErrorKind::AddrInUse => {
        continue;
    }
    Err(e) => {
        std::fs::remove_file(bind_filepath)?;
        return Err(e.into());
    }
```

**Comment by spease** [comment]
Looked at it a bit more closely. I think the issue I was encountering was if there was a dead file, eg if there was an unexpected process kill or shutdown but the file for the socket still existed.

This is actually duplicating the logic from wpa_supplicant itself:
https://w1.fi/cgit/hostap/tree/src/common/wpa_ctrl.c#n94

```
	if (bind(ctrl->s, (struct sockaddr *) &ctrl->local,
		    sizeof(ctrl->local)) < 0) {
		if (errno == EADDRINUSE && tries < 2) {
			/*
			 * getpid() returns unique identifier for this instance
			 * of wpa_ctrl, so the existing socket file must have
			 * been left by unclean termination of an earlier run.
			 * Remove the file and try again.
			 */
			unlink(ctrl->local.sun_path);
			goto try_again;
		}
```

**Comment by apbr** [comment]
Hmm, good point.
The difference I see between wpa_ctrl_rs and the wpa_ctrl from wpa_supplicant is that the wpa_supplicant version has two counters:
- `tries` which is the same as `counter` in your code, but is not used for the socket name. (https://w1.fi/cgit/hostap/tree/src/common/wpa_ctrl.c#n101)
- `counter` which is incremented each time `open()` is called.  (https://w1.fi/cgit/hostap/tree/src/common/wpa_ctrl.c#n98) This variable is used for the socket name and ensures that each open call uses a different socket name.

So I guess wpa_ctrl_rs needs some state so that it can use a new socket name each time open is called.

**Comment by spease** [comment]
Good catch. Yeah, looks like I somehow merged the two counters when implementing it. This looks like an easy fix but it's not top of my priority list right now. If you can submit a PR I'd be happy to merge it. Sorry this has been dragging on.

**Comment by apbr** [comment]
If we want to replicate the behavior of the wpa_supplicant version, we need to store some state. In wpa_supplicant this is done by declaring `counter` static.
For this crate we probably need a lazy_static Mutex for that.
What do you think?

**Comment by spease** [comment]
I would use `std::sync::atomic::AtomicU32`. Or `AtomicUsize` if you want to lean a bit more towards idiomatic with Rust rather than strict compliance with the C++ code. They're both simpler to implement and I think more performant where CPUs have the right hardware instructions to do atomic operations directly.
